In [165]:
import numpy as np
from sklearn.datasets import make_classification
import seaborn as sns

In [166]:
X, y = make_classification(n_samples = 1000, n_features=2, n_redundant=0, n_informative=2,
                             n_clusters_per_class=1, n_classes=2, random_state=67)

In [167]:
class KNNClassifier:
    def __init__(self, k:int) -> None:
        if k <= 0:
            raise ValueError('k must be a positive number')
        self.k = k
    
    def fit(self, X, y) -> 'KNNClassifier':
        self.x = X
        self.y = y
        
        return self
    
    def predict(self, points) -> int:
        predicted_labels = []
        
        for point in points:
            distances = np.linalg.norm(self.x - point, axis=1)
            neighbors_indexes = distances.argsort()[:self.k] 
            neighbors_labels = self.y[neighbors_indexes]

            labels_to_num = {label : np.count_nonzero(neighbors_labels == label) for label in set(neighbors_labels)}
            labels_to_num = sorted(labels_to_num.items(), key=lambda x: x[1], reverse=True)

            predicted_labels.append(labels_to_num[0][0])
            
        return np.array(predicted_labels)

In [168]:
my_instance = KNNClassifier(k=150).fit(X, y)

In [169]:
from sklearn.neighbors import KNeighborsClassifier 

In [170]:
instance = KNeighborsClassifier(n_neighbors=150)

In [171]:
instance.fit(X, y)

KNeighborsClassifier(n_neighbors=150)

In [172]:
x = np.linspace(-1.5, 2, 50)
y = np.linspace(-4, 1, 50)

In [180]:
test_points = [np.array([x[i], y[i]]) for i in range(len(x))]

In [181]:
np.random.shuffle(test_points)

In [182]:
test_points

[array([-0.14285714, -2.06122449]),
 array([-1.07142857, -3.3877551 ]),
 array([-0.35714286, -2.36734694]),
 array([1.78571429, 0.69387755]),
 array([ 0.5       , -1.14285714]),
 array([ 0.42857143, -1.24489796]),
 array([-1.42857143, -3.89795918]),
 array([1.5       , 0.28571429]),
 array([-0.5       , -2.57142857]),
 array([1.35714286, 0.08163265]),
 array([-1.14285714, -3.48979592]),
 array([ 0.35714286, -1.34693878]),
 array([-0.42857143, -2.46938776]),
 array([1.85714286, 0.79591837]),
 array([-0.64285714, -2.7755102 ]),
 array([ 0.        , -1.85714286]),
 array([-1.5, -4. ]),
 array([-0.71428571, -2.87755102]),
 array([ 0.64285714, -0.93877551]),
 array([ 0.85714286, -0.63265306]),
 array([ 1.21428571, -0.12244898]),
 array([-0.92857143, -3.18367347]),
 array([ 0.92857143, -0.53061224]),
 array([ 0.14285714, -1.65306122]),
 array([ 0.71428571, -0.83673469]),
 array([ 1.07142857, -0.32653061]),
 array([-1.21428571, -3.59183673]),
 array([-0.85714286, -3.08163265]),
 array([-0.571

In [185]:
my_predictions = my_instance.predict(test_points)

In [186]:
predictions = instance.predict(test_points)

In [187]:
(my_predictions == predictions).all()

True